"""copy_text.py — every word on the page, English and Thai, written by hand.
research/facts.md holds the sources behind every fact."""
import json
import os

UI = {"en": {}, "th": {}}

# a petal from a strip of leaf 1 wide and 1.7 long; each fold moves the part left of a→b over onto the rest
LINES = [None, [[-0.5, 1.2], [0, 1.7]], [[0, 1.7], [0.5, 1.2]], [[0, 0], [0, 1.7]]]

UI["en"].update({
    "title": "Krathong, Drawn", "other_title": "กระทง วาดด้วยคณิต",
    "desc": "How a krathong is folded from banana leaf, why it floats and stays upright, and where the Ping carries it after Loy Krathong, drawn with math.",
    "card_alt": "Krathongs with candles drifting down the Ping River at night under a full moon, drawn with math",
    "hero_alt": "The Ping River at night with krathongs drifting downstream, candles lit",
    "kicker": "Loy Krathong · Yi Peng · the Ping",
    "lede": "A slice of banana trunk, folded leaf, flowers, a candle and three sticks of incense. How the petals are folded, why it floats, and where the river takes it, drawn with the same sums the water uses.",
    "hint": "Tap the water to float one.",
    "cardline": "Folding the leaf, floating, and the river",
    "nav_label": "Sections",
    "nav": [("what", "What it is"), ("fold", "Fold a petal"), ("rings", "Rings"), ("float", "Will it float"), ("river", "Downstream"), ("after", "The morning after"), ("yipeng", "2026"), ("words", "Words"), ("sources", "Sources")],
    "lang_this": "EN", "lang_other": "ไทย",
    "fo_kick": "Fold a petal", "fo_h": "Three folds make a point",
    "fo_p": ["A strip of banana leaf, folded corner to middle on one side, then the other, then in half. Each fold turns part of the leaf over a straight line, half a turn, so it lands face down on the rest."],
    "fo_p2": ["Fold one corner down to the middle line and the edge turns through 45°. Fold the other corner and the two meet in a point with a right angle at the tip. Fold that in half and the tip closes to 45°, a sharp petal with two layers on each side, stiff enough to stand."],
    "fo_note": "The shiny face of the leaf is dark green and the matt back is light. The thin lines are the leaf's veins: each one is a straight line on the flat strip and stays straight through every fold.",
    "play": "Fold it",
    "fold_steps": [
        {"text": "A strip of banana leaf, shiny side up. The veins run along it."},
        {"text": "Fold the top left corner down to the middle line. The fold runs at 45°."},
        {"text": "Fold the top right corner down to meet it. The tip is now a right angle, 90°."},
        {"text": "Fold the left half over onto the right. The tip closes to 45°, four layers thick near the point."},
    ],
    "ri_kick": "Rings", "ri_h": "How many petals go round",
    "ri_p": ["Petals go round the base in rings, each one tucked under the next. The rim of a ring is 2πr long, and each petal takes up its width less the part hidden under its neighbour. Each ring sits a little inside the one below, half a petal round, so the points of one ring fall between the points of the next."],
    "ri_eq": "petals in a ring = ⌊ 2πr ÷ (w × (1 − overlap)) ⌋",
    "r_d": "Base across", "r_w": "Petal width", "r_n": "Rings", "r_l": "Overlap",
    "r_per": "Petals, ring by ring", "r_tot": "Petals in all", "r_leaf": "Pins, one a petal",
    "ri_note": "Each ring here is 17% smaller across than the one under it.",
    "fl_kick": "Will it float", "fl_h": "Down until it has pushed aside its own weight",
    "fl_p": ["A krathong sinks into the river until the water it pushes aside weighs as much as the krathong. For a round base that gives the depth at the waterline. What is left of the base above the water is how much more it can carry.",
             "Floating is half of it. It also has to stay upright. Tip it a little and the water under it shifts to the low side, pushing back. That push acts through a point called the metacentre, M. While M sits above the centre of all the krathong's weight, G, it rights itself."],
    "fl_eq": "depth = mass ÷ (ρ<sub>water</sub> × πr²) &nbsp;&nbsp; GM = KB + r² ÷ (4 × depth) − KG",
    "b_d": "Base across", "b_t": "Base thickness", "b_rho": "Banana trunk, density", "b_l": "Leaves, flowers, candle", "b_h": "Candle height",
    "b_coin": "Add five ฿1 coins", "b_clear": "Take the coins off",
    "b_mass": "All of it weighs", "b_sink": "Under the water", "b_free": "Above the water", "b_gm": "M above G", "b_heel": "Lean in a 3 m/s breeze",
    "b_count": "Coins on it", "b_left": "฿1 coins to sink it",
    "b_g": "G, centre of weight", "b_m": "M, metacentre",
    "b_ok": "Floats upright.", "b_tips": "Floats, but tips over: G is above M.", "b_sunk": "The water comes over the top.",
    "coin_g": 3,
    "fl_p2": ["A wide base is very hard to tip: the r² in the sum grows fast. A narrow base with a tall candle is the one that rolls over."],  # stylecheck: allow — "tip" is the float tipping over, physics
    "fl_note": "FACTS-PENDING",
    "rho_default": 600,
    "rv_kick": "Downstream", "rv_h": "Fast in the middle, slow at the banks",
    "rv_p": ["Water drags on the riverbed and the banks, so it runs fastest in the middle of the river and slowest at the edges. Sixty krathongs, let go from one bank, wander out into the current a little at a time. Some get caught where the water barely moves."],
    "rv_eq": "speed = u<sub>max</sub> × (1 − |2y ÷ W|<sup>p</sup>)",
    "v_max": "Speed in the middle", "v_p": "Shape of the current (p)", "v_again": "Let them go again",
    "v_clock": "River time", "v_mean": "Average across", "v_1h": "Middle, in one hour", "v_night": "Middle, by morning (8 h)", "v_stuck": "Caught at the bank",
    "v_moving": "drifting", "v_caught": "caught at the bank",
    "rv_p2": ["A bigger p means a flat, even current across most of the river with the slowing squeezed against the banks; p = 2 is the smooth curve of a slow, deep channel. The average speed across the river is u<sub>max</sub> × p ÷ (p + 1)."],
    "rv_note": "The river is drawn 90 m wide. Each krathong takes a small random step across the current every moment, so where it ends up is a matter of luck as well as speed.",
    "ping_src": "https://motdang.net/data/ping.json",
    "af_kick": "The morning after", "af_h": "Counted the next day",
    "af_p": [], "af_p2": [], "af_note": "", "a_nat": "natural", "a_foam": "foam",
    "sib_h": "Khom Loi, Drawn", "sib_p": " The same night in the sky: why a lantern rises, how high it goes, and where it lands.",
    "words_h": "Words", "src_h": "Sources", "src_p": "Where the facts on this page come from.",
    "pic_kick": "Pictures", "pic_h": "Krathongs, made and floated",
    "foot": "Krathong, Drawn · text CC BY 4.0 · code MIT",
})

UI["th"].update({
    "title": "กระทง วาดด้วยคณิต", "other_title": "Krathong, Drawn",
    "desc": "กระทงพับจากใบตองอย่างไร ทำไมลอยน้ำได้และไม่คว่ำ แล้วแม่น้ำปิงพาไปไหนหลังคืนลอยกระทง วาดด้วยคณิต",
    "card_alt": "กระทงจุดเทียนลอยไปตามแม่น้ำปิงตอนกลางคืนใต้พระจันทร์เต็มดวง วาดด้วยคณิต",
    "hero_alt": "แม่น้ำปิงตอนกลางคืน กระทงจุดเทียนลอยไปตามน้ำ",
    "kicker": "ลอยกระทง · ยี่เป็ง · แม่น้ำปิง",
    "lede": "หยวกกล้วยหนึ่งแว่น ใบตองพับ ดอกไม้ เทียนหนึ่งเล่ม ธูปสามดอก พับกลีบอย่างไร ทำไมลอยได้ และแม่น้ำพาไปไหน วาดด้วยสูตรเดียวกับที่น้ำใช้",
    "hint": "แตะที่น้ำเพื่อลอยกระทง",
    "cardline": "พับใบตอง ลอยน้ำ และสายน้ำ",
    "nav_label": "หัวข้อ",
    "nav": [("what", "กระทงคืออะไร"), ("fold", "พับกลีบ"), ("rings", "กลีบเป็นวง"), ("float", "ลอยไหม"), ("river", "ตามน้ำ"), ("after", "เช้าวันรุ่งขึ้น"), ("yipeng", "2569"), ("words", "คำศัพท์"), ("sources", "ที่มา")],
    "lang_this": "ไทย", "lang_other": "EN",
    "fo_kick": "พับกลีบ", "fo_h": "พับสามทีได้ปลายแหลม",
    "fo_p": ["ใบตองหนึ่งชิ้น พับมุมเข้าหาเส้นกลางข้างหนึ่ง แล้วอีกข้าง แล้วพับครึ่ง การพับแต่ละครั้งคือการหมุนใบตองส่วนหนึ่งข้ามเส้นตรงไปครึ่งรอบ ให้คว่ำทับส่วนที่เหลือ"],
    "fo_p2": ["พับมุมแรกลงมาถึงเส้นกลาง ขอบใบตองหมุนไป 45° พับอีกมุม สองมุมมาชนกันเป็นปลายแหลม ปลายเป็นมุมฉาก 90° แล้วพับครึ่ง ปลายหุบเหลือ 45° ได้กลีบแหลม แต่ละข้างหนาสองชั้น แข็งพอจะตั้งได้"],
    "fo_note": "ด้านมันของใบตองเป็นสีเขียวเข้ม ด้านหลังที่ด้านเป็นสีอ่อน เส้นบาง ๆ คือเส้นใบ แต่ละเส้นเป็นเส้นตรงบนแผ่นแบน และยังตรงอยู่ทุกครั้งที่พับ",
    "play": "พับเลย",
    "fold_steps": [
        {"text": "ใบตองหนึ่งชิ้น ด้านมันอยู่ข้างบน เส้นใบวิ่งไปตามยาว"},
        {"text": "พับมุมบนซ้ายลงมาถึงเส้นกลาง รอยพับเอียง 45°"},
        {"text": "พับมุมบนขวาลงมาชนกัน ปลายตอนนี้เป็นมุมฉาก 90°"},
        {"text": "พับครึ่งซีกซ้ายทับซีกขวา ปลายหุบเหลือ 45° ใกล้ปลายหนาสี่ชั้น"},
    ],
    "ri_kick": "กลีบเป็นวง", "ri_h": "รอบหนึ่งใส่กลีบได้กี่กลีบ",
    "ri_p": ["กลีบเรียงรอบฐานเป็นวง แต่ละกลีบสอดใต้กลีบถัดไป ขอบวงยาว 2πr แต่ละกลีบกินที่เท่าความกว้างของมัน ลบส่วนที่ซ่อนอยู่ใต้กลีบข้าง ๆ วงที่สูงขึ้นไปจะเล็กลงนิดหนึ่ง และเลื่อนไปครึ่งกลีบ ปลายกลีบวงหนึ่งเลยตกอยู่ระหว่างปลายกลีบอีกวง"],
    "ri_eq": "กลีบในหนึ่งวง = ⌊ 2πr ÷ (w × (1 − ส่วนที่ซ้อน)) ⌋",
    "r_d": "ฐานกว้าง", "r_w": "กลีบกว้าง", "r_n": "จำนวนวง", "r_l": "ส่วนที่ซ้อนกัน",
    "r_per": "กลีบ ทีละวง", "r_tot": "กลีบทั้งหมด", "r_leaf": "ไม้กลัด กลีบละอัน",
    "ri_note": "แต่ละวงในภาพเล็กกว่าวงข้างล่าง 17%",
    "fl_kick": "ลอยไหม", "fl_h": "จมลงจนเบียดน้ำได้เท่าน้ำหนักตัวเอง",
    "fl_p": ["กระทงจมลงไปในแม่น้ำ จนน้ำที่มันเบียดออกไปหนักเท่ากับตัวกระทง ฐานกลม ๆ เลยบอกได้ว่าจมลึกแค่ไหน ส่วนของฐานที่ยังโผล่พ้นน้ำ คือที่ว่างให้บรรทุกเพิ่มได้",
             "ลอยได้เป็นแค่ครึ่งเดียว ต้องไม่คว่ำด้วย ถ้าเอียงนิดหนึ่ง น้ำข้างใต้จะดันขึ้นทางด้านที่ต่ำมากกว่า แรงดันนี้ผ่านจุดที่เรียกว่าเมตาเซนเตอร์ M ตราบใดที่ M อยู่สูงกว่าจุดศูนย์ถ่วงของกระทงทั้งใบ G กระทงจะตั้งตรงกลับมาเอง"],
    "fl_eq": "ลึก = มวล ÷ (ρ<sub>น้ำ</sub> × πr²) &nbsp;&nbsp; GM = KB + r² ÷ (4 × ลึก) − KG",
    "b_d": "ฐานกว้าง", "b_t": "ฐานหนา", "b_rho": "ความหนาแน่นของหยวกกล้วย", "b_l": "ใบตอง ดอกไม้ เทียน", "b_h": "เทียนสูง",
    "b_coin": "ใส่เหรียญบาท 5 เหรียญ", "b_clear": "เอาเหรียญออก",
    "b_mass": "หนักทั้งหมด", "b_sink": "จมใต้น้ำ", "b_free": "พ้นน้ำ", "b_gm": "M สูงกว่า G", "b_heel": "เอียงเมื่อลม 3 ม./วินาที",
    "b_count": "เหรียญบนกระทง", "b_left": "เหรียญบาทที่ทำให้จม",
    "b_g": "G จุดศูนย์ถ่วง", "b_m": "M เมตาเซนเตอร์",
    "b_ok": "ลอยตั้งตรง", "b_tips": "ลอยได้ แต่คว่ำ เพราะ G อยู่สูงกว่า M", "b_sunk": "น้ำท่วมขึ้นมาถึงข้างบนแล้ว",
    "fl_p2": ["ฐานกว้างทำให้คว่ำยากมาก เพราะ r² ในสูตรโตเร็ว ฐานแคบกับเทียนสูงคือแบบที่พลิกคว่ำ"],
    "fl_note": "FACTS-PENDING",
    "rv_kick": "ตามน้ำ", "rv_h": "กลางแม่น้ำเร็ว ริมตลิ่งช้า",
    "rv_p": ["น้ำเสียดสีกับท้องน้ำและตลิ่ง กลางแม่น้ำเลยไหลเร็วที่สุด ริมตลิ่งช้าที่สุด กระทงหกสิบใบ ปล่อยจากตลิ่งเดียวกัน ค่อย ๆ ลอยออกไปหากระแสน้ำทีละนิด บางใบไปติดตรงที่น้ำแทบไม่ไหล"],
    "rv_eq": "ความเร็ว = u<sub>max</sub> × (1 − |2y ÷ W|<sup>p</sup>)",
    "v_max": "ความเร็วกลางแม่น้ำ", "v_p": "รูปของกระแสน้ำ (p)", "v_again": "ปล่อยใหม่",
    "v_clock": "เวลาบนแม่น้ำ", "v_mean": "เฉลี่ยทั้งความกว้าง", "v_1h": "กลางแม่น้ำ ในหนึ่งชั่วโมง", "v_night": "กลางแม่น้ำ ถึงเช้า (8 ชม.)", "v_stuck": "ติดอยู่ริมตลิ่ง",
    "v_moving": "ลอยไป", "v_caught": "ติดริมตลิ่ง",
    "rv_p2": ["ค่า p มาก แปลว่ากระแสน้ำเรียบเท่ากันเกือบทั้งแม่น้ำ แล้วช้าลงเฉพาะชิดตลิ่ง p = 2 คือโค้งเรียบของร่องน้ำลึกที่ไหลช้า ความเร็วเฉลี่ยทั้งความกว้างคือ u<sub>max</sub> × p ÷ (p + 1)"],
    "rv_note": "แม่น้ำในภาพกว้าง 90 เมตร กระทงแต่ละใบขยับข้ามกระแสน้ำแบบสุ่มนิดหนึ่งทุกขณะ จะไปจบที่ไหนจึงขึ้นกับดวงพอ ๆ กับความเร็ว",
    "af_kick": "เช้าวันรุ่งขึ้น", "af_h": "นับกันวันรุ่งขึ้น",
    "af_p": [], "af_p2": [], "af_note": "", "a_nat": "วัสดุธรรมชาติ", "a_foam": "โฟม",
    "sib_h": "โคมลอย วาดด้วยคณิต", "sib_p": " คืนเดียวกันบนท้องฟ้า โคมลอยขึ้นเพราะอะไร ขึ้นสูงแค่ไหน และไปตกที่ไหน",
    "words_h": "คำศัพท์", "src_h": "ที่มา", "src_p": "ข้อมูลในหน้านี้มาจากที่เหล่านี้",
    "pic_kick": "ภาพ", "pic_h": "กระทง ตอนทำและตอนลอย",
    "foot": "กระทง วาดด้วยคณิต · ข้อความ CC BY 4.0 · โค้ด MIT",
})

# Bangkok's count the morning after (BMA): year, natural, foam, bread (counted on its own from 2025)
COUNTS = [
    (2015, 754587, 71027, 0), (2016, 617901, 44034, 0), (2017, 760019, 51926, 0), (2018, 796444, 44883, 0),
    (2019, 483264, 18760, 0), (2020, 474806, 17731, 0), (2021, 388954, 14281, 0), (2022, 548086, 24516, 0),
    (2023, 618951, 20877, 0), (2024, 506320, 8270, 0), (2025, 323626, 28298, 39103),
]
_first, _last = COUNTS[0], COUNTS[-1]
_tot = lambda r: r[1] + r[2] + r[3]
FOAM_FIRST = 100 * _first[2] / _tot(_first)
FOAM_LOW = min(COUNTS, key=lambda r: r[2] / _tot(r))
DROP = 100 * (1 - _tot(_last) / _tot(_first))

UI["en"].update({
    "what_kick": "What it is", "what_h": "A lotus of leaf on a slice of trunk",
    "what_p": [
        "The old base is a slice of banana trunk, หยวกกล้วย <i>yuak kluai</i>, cut about 1.5 to 2 inches thick. Strips of banana leaf, ใบตอง <i>bai tong</i>, are folded into petals and pinned round its rim. The best leaf for folding is from กล้วยตานี, <i>kluai tani</i>: glossy, dark green, tough and soft, hard to tear. On top go flowers, a candle and three sticks of incense. Some people add coins, or a cut fingernail or a few hairs to shed bad luck.",
        "The Department of Cultural Promotion lists the reasons people give for floating one: to honour the Buddha's footprint on the sandbank of the Narmada river in India; to thank Phra Mae Khongkha, the mother of water, and ask her pardon for using and dirtying it; to float bad luck away; to make a wish; to remember the dead. The story of Nang Noppamat, who folded the first leaf krathong for Phra Ruang of Sukhothai, comes from a book that Prince Damrong dated to the reign of Rama III.",
        "In Lanna the night is Yi Peng, the full moon of the second Lanna month. Chiang Mai's National Museum tells of <i>loi khamot</i>, floating fire: Mon people of Hariphunchai, about 1,000 years ago, floated flowers, candles and goods in boat-shaped <i>sapao</i> down the Ping to remember kin they had left in Pegu. Princess Dara Rasmi floated candles on coconut-husk boats in Chiang Mai around 1917–1927; the leaf krathong caught on after 1947, and from 1969 the big-krathong parade has run to Nawarat Bridge.",
    ],
    "fo_p": ["A strip of banana leaf about 1.5 inches (3.8 cm) wide. Fold the two top corners down so their edges meet in the middle, then fold it in half: this is how a กลีบกุหลาบ, <i>klip kulap</i> or rose petal, begins. Each fold turns part of the leaf over a straight line, half a turn, so it lands face down on the rest."],
    "fo_p2": ["Fold one corner down to the middle line and the edge turns through 45°. Fold the other corner and the two meet in a point with a right angle at the tip. Fold that in half and the tip closes to 45°. For a rose petal the folded spine is then rolled into a curve, and petals are slipped one into the next and sewn into a long band that wraps the rim like a crown. A craft book from 2012 lists more than 70 named petals, among them กลีบผกา <i>klip phaka</i>, กลีบเล็บมือนาง <i>klip lep mue nang</i> (the lady's fingernail) and a Lanna-style กลีบหน้านาค, the naga face."],
    "fo_note": "The shiny face of the leaf is dark green and the matt back is light. The thin lines are the leaf's veins: each one is a straight line on the flat strip and stays straight through every fold. Only the top of the strip is drawn; the rest, about 15 cm long in all, is trimmed at the base.",
    "fold_steps": [
        {"text": "The top of a strip of banana leaf, shiny side up."},
        {"text": "Fold the top left corner down to the middle line. The fold runs at 45°."},
        {"text": "Fold the top right corner down to meet it. The tip is now a right angle, 90°."},
        {"text": "Fold the left half over onto the right. The tip closes to 45°, four layers thick near the point."},
    ],
    "ri_p": ["Petals go round the base in rings, each tucked into the next. How many depends on the size of the base. The rim of a ring is 2πr long, and each petal takes up its width less the part hidden under its neighbour. Each ring here sits a little inside the one below and half a petal round, so the points of one ring fall between the points of the next, as they do in photographs of krathongs."],
    "fl_note": "Nobody has published the density of a fresh slice of banana trunk. Its fibres are denser than water, 1.1 to 1.5 g/cm³; it floats because of the air spaces between its sheaths. The 600 kg/m³ here is the page's guess: move it and see. A ฿1 coin is taken as 3 g.",
    "rho_default": 600,
    "rv_p": ["Water drags on the riverbed and the banks, so it runs fastest in the middle of the river and slowest at the edges. Sixty krathongs, let go from one bank, wander out into the current a little at a time. Some get caught where the water barely moves."],
    "rv_p2": [
        "At Nawarat Bridge the Royal Irrigation Department's gauge, P.1, has measured the Ping since 1921. Its November average is about 62 m³ of water a second. At a usual November flow the river there is about 80 m wide, and the water moves 0.5 to 0.7 m/s on average across it, worked from the department's rating curve and its 2025 survey of the riverbed. That is 2 km or so an hour.",
        "A bigger p means an even current across most of the river with the slowing squeezed against the banks. The average speed across the river is u<sub>max</sub> × p ÷ (p + 1). Krathongs that make it downstream pile up at the Tha Wang Tan weir, where volunteers clear them.",
    ],
    "rv_note": "The river is drawn 80 m wide. Each krathong takes a small random step across the current every moment, so where it ends up is luck as well as speed.",
    "af_p": [f"Bangkok counts the krathongs it pulls out of its rivers and canals the next morning. In {_first[0]} it collected {_tot(_first):,}; in {_last[0]}, {_tot(_last):,}, {DROP:.0f}% fewer. Foam was {FOAM_FIRST:.1f}% of the count in {_first[0]} and its lowest share, {100 * FOAM_LOW[2] / _tot(FOAM_LOW):.1f}%, came in {FOAM_LOW[0]}."],
    "af_p2": [f"In {_last[0]} the city counted bread krathongs on their own for the first time: {_last[3]:,}. The city's environment office gives banana trunk and leaf about 14 days to break down, bread and ice-cream cones about 3 days, and foam about 50 years. A search of Thai and English news from 2013 to 2025 turned up no count for Chiang Mai."],
    "af_note": "Counts from Bangkok Metropolitan Administration figures as reported by Thai PBS, Sanook, InfoQuest, Thairath, PPTV, Khaosod English and the Bangkok Post. 2015 and 2016 are from English-language reports.",
    "a_bread": "bread",
    "yp_kick": "2026", "yp_h": "Tuesday 24 November",
    "yp_p": ["Loy Krathong 2026 falls on Tuesday 24 November, the fifteenth night of the waxing moon of the twelfth month. Chiang Mai city's Yi Peng runs 23 to 25 November:"],
    "dates": [
        ("Mon 23 Nov", "the city's Yi Peng begins"),
        ("Tue 24 Nov", "full moon, 21:53; Loy Krathong"),
        ("Wed 25 Nov", "the big-krathong parade"),
    ],
    "yp_p2": [
        "In 2025 the city floated from Tha Phae Gate, Tha Phae Road, the municipal offices, the Mae Kha canal and Si Khong landing, and from the foot of Nawarat Bridge. The municipality ties bamboo rafts on the Ping near its offices for people to float from.",
        "The city has asked hotels to stop guests letting sky lanterns go inside the city.",
    ],
    "words": [
        ("กระทง", "krathong", "the float"),
        ("ลอยกระทง", "loi krathong", "to float a krathong; the festival"),
        ("หยวกกล้วย", "yuak kluai", "banana trunk, the base"),
        ("ใบตอง", "bai tong", "banana leaf"),
        ("กล้วยตานี", "kluai tani", "the banana whose leaf folds best"),
        ("กลีบ", "klip", "petal"),
        ("กลีบกุหลาบ", "klip kulap", "rose petal, folded and rolled"),
        ("กลีบผกา", "klip phaka", "a folded petal, often stacked in threes"),
        ("ตับ", "tap", "a set of three stacked petals"),
        ("หมุด", "mut", "pin"),
        ("ธูป", "thup", "incense stick"),
        ("เทียน", "thian", "candle"),
        ("สะเดาะเคราะห์", "sado khro", "to shed bad luck"),
        ("พระแม่คงคา", "phra mae khongkha", "the mother of water"),
        ("ยี่เป็ง", "yi peng", "full moon of the second Lanna month"),
        ("ลอยโขมด", "loi khamot", "Lanna: floating fire"),
        ("สะเปา", "sapao", "Lanna: a boat-shaped krathong loaded with gifts"),
        ("กระทงหน้อย", "krathong noi", "Lanna: a small krathong"),
        ("กระทงใหญ่", "krathong yai", "a big parade krathong"),
        ("สะพานนวรัฐ", "saphan nawarat", "Nawarat Bridge"),
    ],
})

UI["th"].update({
    "what_kick": "กระทงคืออะไร", "what_h": "ดอกบัวใบตองบนแว่นหยวกกล้วย",
    "what_p": [
        "ฐานแบบดั้งเดิมคือหยวกกล้วยตัดเป็นแว่น หนาราว 1.5–2 นิ้ว ใบตองฉีกเป็นชิ้นแล้วพับเป็นกลีบ กลัดรอบขอบฐาน ใบตองที่พับง่ายที่สุดคือใบตองตานี ผิวมัน สีเขียวเข้ม เหนียวนุ่ม ไม่ฉีกง่าย ข้างบนใส่ดอกไม้ เทียนหนึ่งเล่ม ธูปสามดอก บางคนใส่เหรียญ ตัดเล็บหรือเส้นผมใส่ลงไปเพื่อสะเดาะเคราะห์",
        "กรมส่งเสริมวัฒนธรรมรวบรวมเหตุผลที่คนลอยกระทงไว้ บูชารอยพระพุทธบาทที่หาดทรายริมแม่น้ำนัมมทาในอินเดีย ขอบคุณและขอขมาพระแม่คงคาที่ได้ใช้น้ำและทำให้น้ำสกปรก ลอยเคราะห์ อธิษฐาน และระลึกถึงผู้ล่วงลับ เรื่องนางนพมาศที่ทำกระทงใบตองใบแรกถวายพระร่วงแห่งสุโขทัย มาจากหนังสือที่สมเด็จฯ กรมพระยาดำรงราชานุภาพทรงสันนิษฐานว่าแต่งในสมัยรัชกาลที่ 3",
        "ในล้านนาคืนนี้คือยี่เป็ง วันเพ็ญเดือนยี่ พิพิธภัณฑสถานแห่งชาติเชียงใหม่เล่าถึงการลอยโขมดหรือลอยไฟ ชาวมอญหริภุญไชยเมื่อราวพันปีก่อน ลอยดอกไม้ เทียน และข้าวของในสะเปาลงแม่น้ำปิง เพื่อระลึกถึงญาติที่อยู่หงสาวดี พระราชชายาเจ้าดารารัศมีทรงลอยเทียนบนเรือกาบมะพร้าวที่เชียงใหม่ราวปี 2460–2470 กระทงใบตองเริ่มนิยมหลังปี 2490 และตั้งแต่ปี 2512 ขบวนกระทงใหญ่ก็แห่ไปถึงสะพานนวรัฐ",
    ],
    "fo_p": ["ใบตองกว้างราว 1.5 นิ้ว (3.8 ซม.) พับมุมบนสองข้างลงมาให้ขอบชนกันตรงกลาง แล้วพับครึ่ง นี่คือขั้นแรกของกลีบกุหลาบ การพับแต่ละครั้งคือการหมุนใบตองส่วนหนึ่งข้ามเส้นตรงไปครึ่งรอบ ให้คว่ำทับส่วนที่เหลือ"],
    "fo_p2": ["พับมุมแรกลงมาถึงเส้นกลาง ขอบใบตองหมุนไป 45° พับอีกมุม สองมุมมาชนกันเป็นปลายแหลม ปลายเป็นมุมฉาก 90° แล้วพับครึ่ง ปลายหุบเหลือ 45° กลีบกุหลาบจะม้วนสันที่พับให้โค้ง แล้วสอดกลีบต่อกันเย็บเป็นแผงยาว พันรอบขอบฐานเหมือนมงกุฎ หนังสืองานใบตองเล่มหนึ่งปี 2555 รวมชื่อกลีบไว้กว่า 70 แบบ เช่น กลีบผกา กลีบเล็บมือนาง และกลีบหน้านาคแบบล้านนา"],
    "fo_note": "ด้านมันของใบตองเป็นสีเขียวเข้ม ด้านหลังที่ด้านเป็นสีอ่อน เส้นบาง ๆ คือเส้นใบ แต่ละเส้นเป็นเส้นตรงบนแผ่นแบน และยังตรงอยู่ทุกครั้งที่พับ ในภาพวาดแค่ปลายบนของใบตอง ส่วนที่เหลือยาวรวมราว 15 ซม. ตัดทิ้งที่ฐาน",
    "fold_steps": [
        {"text": "ปลายบนของใบตองหนึ่งชิ้น ด้านมันอยู่ข้างบน"},
        {"text": "พับมุมบนซ้ายลงมาถึงเส้นกลาง รอยพับเอียง 45°"},
        {"text": "พับมุมบนขวาลงมาชนกัน ปลายตอนนี้เป็นมุมฉาก 90°"},
        {"text": "พับครึ่งซีกซ้ายทับซีกขวา ปลายหุบเหลือ 45° ใกล้ปลายหนาสี่ชั้น"},
    ],
    "ri_p": ["กลีบเรียงรอบฐานเป็นวง แต่ละกลีบสอดเข้ากลีบถัดไป จะใช้กี่กลีบขึ้นกับขนาดฐาน ขอบวงยาว 2πr แต่ละกลีบกินที่เท่าความกว้างของมัน ลบส่วนที่ซ่อนอยู่ใต้กลีบข้าง ๆ วงที่สูงขึ้นไปในภาพจะเล็กลงนิดหนึ่งและเลื่อนไปครึ่งกลีบ ปลายกลีบวงหนึ่งเลยตกอยู่ระหว่างปลายกลีบอีกวง เหมือนในภาพถ่ายกระทง"],
    "fl_note": "ยังไม่มีใครตีพิมพ์ความหนาแน่นของหยวกกล้วยสด เส้นใยของมันหนักกว่าน้ำ 1.1–1.5 กรัมต่อ ลบ.ซม. ที่ลอยได้เพราะมีช่องอากาศระหว่างกาบ ค่า 600 กก./ลบ.ม. ในหน้านี้เป็นค่าที่เดาเอง ลองเลื่อนดู เหรียญบาทคิดหนัก 3 กรัม",
    "rv_p": ["น้ำเสียดสีกับท้องน้ำและตลิ่ง กลางแม่น้ำเลยไหลเร็วที่สุด ริมตลิ่งช้าที่สุด กระทงหกสิบใบ ปล่อยจากตลิ่งเดียวกัน ค่อย ๆ ลอยออกไปหากระแสน้ำทีละนิด บางใบไปติดตรงที่น้ำแทบไม่ไหล"],
    "rv_p2": [
        "ที่สะพานนวรัฐ สถานีวัดน้ำ P.1 ของกรมชลประทานวัดแม่น้ำปิงมาตั้งแต่ปี 2464 เดือนพฤศจิกายนเฉลี่ยน้ำไหลราว 62 ลูกบาศก์เมตรต่อวินาที ที่ปริมาณน้ำปกติของเดือนนี้ แม่น้ำตรงนั้นกว้างราว 80 เมตร น้ำไหลเฉลี่ยทั้งหน้าตัด 0.5–0.7 เมตรต่อวินาที คิดจากโค้งความสัมพันธ์ระดับน้ำกับปริมาณน้ำของกรม และผลสำรวจท้องน้ำปี 2568 ราวชั่วโมงละ 2 กม.",
        "ค่า p มาก แปลว่ากระแสน้ำเท่ากันเกือบทั้งแม่น้ำ แล้วช้าลงเฉพาะชิดตลิ่ง ความเร็วเฉลี่ยทั้งความกว้างคือ u<sub>max</sub> × p ÷ (p + 1) กระทงที่ลอยไปถึงปลายน้ำจะไปกองที่ประตูระบายน้ำท่าวังตาล ที่อาสาสมัครไปช่วยกันเก็บ",
    ],
    "rv_note": "แม่น้ำในภาพกว้าง 80 เมตร กระทงแต่ละใบขยับข้ามกระแสน้ำแบบสุ่มนิดหนึ่งทุกขณะ จะไปจบที่ไหนจึงขึ้นกับดวงพอ ๆ กับความเร็ว",
    "af_p": [f"กรุงเทพมหานครนับกระทงที่เก็บขึ้นจากแม่น้ำลำคลองทุกเช้าหลังวันลอยกระทง ปี {_first[0] + 543} เก็บได้ {_tot(_first):,} ใบ ปี {_last[0] + 543} เก็บได้ {_tot(_last):,} ใบ น้อยลง {DROP:.0f}% ปี {_first[0] + 543} กระทงโฟมเป็น {FOAM_FIRST:.1f}% ของทั้งหมด ต่ำสุดที่ {100 * FOAM_LOW[2] / _tot(FOAM_LOW):.1f}% ในปี {FOAM_LOW[0] + 543}"],
    "af_p2": [f"ปี {_last[0] + 543} กทม. นับกระทงขนมปังแยกเป็นครั้งแรก {_last[3]:,} ใบ สำนักสิ่งแวดล้อมให้ตัวเลขว่า หยวกกล้วยและใบตองย่อยสลายในราว 14 วัน ขนมปังและโคนไอศกรีมราว 3 วัน โฟมราว 50 ปี ค้นข่าวไทยและอังกฤษปี 2556–2568 แล้ว ไม่พบตัวเลขของเชียงใหม่"],
    "af_note": "ตัวเลขของกรุงเทพมหานคร ตามที่ไทยพีบีเอส สนุก อินโฟเควสท์ ไทยรัฐ พีพีทีวี ข่าวสดอิงลิช และบางกอกโพสต์รายงาน ปี 2558 และ 2559 มาจากข่าวภาษาอังกฤษ",
    "a_bread": "ขนมปัง",
    "yp_kick": "2569", "yp_h": "วันอังคารที่ 24 พฤศจิกายน",
    "yp_p": ["ลอยกระทงปี 2569 ตรงกับวันอังคารที่ 24 พฤศจิกายน ขึ้น 15 ค่ำ เดือน 12 ประเพณียี่เป็งของเทศบาลนครเชียงใหม่จัด 23–25 พฤศจิกายน"],
    "dates": [
        ("จ. 23 พ.ย.", "เริ่มงานยี่เป็งของเทศบาล"),
        ("อ. 24 พ.ย.", "เพ็ญ 21:53 น. คืนลอยกระทง"),
        ("พ. 25 พ.ย.", "ขบวนแห่กระทงใหญ่"),
    ],
    "yp_p2": [
        "ปี 2568 คนในเมืองลอยกระทงที่ข่วงประตูท่าแพ ถนนท่าแพ สำนักงานเทศบาล คลองแม่ข่า ท่าน้ำศรีโขง และเชิงสะพานนวรัฐ เทศบาลผูกแพไม้ไผ่ไว้ในแม่น้ำปิงหน้าสำนักงานให้คนลงไปลอย",
        "เทศบาลขอให้โรงแรมห้ามแขกปล่อยโคมลอยในเขตเมือง",
    ],
    "words": [
        ("กระทง", "krathong", "สิ่งที่ลอยน้ำ"),
        ("ลอยกระทง", "loi krathong", "ลอยกระทง ชื่อประเพณี"),
        ("หยวกกล้วย", "yuak kluai", "ต้นกล้วย ใช้ทำฐาน"),
        ("ใบตอง", "bai tong", "ใบกล้วย"),
        ("กล้วยตานี", "kluai tani", "กล้วยที่ใบพับง่ายที่สุด"),
        ("กลีบ", "klip", "กลีบ"),
        ("กลีบกุหลาบ", "klip kulap", "พับแล้วม้วนสัน"),
        ("กลีบผกา", "klip phaka", "กลีบพับ มักซ้อนกันสามกลีบ"),
        ("ตับ", "tap", "กลีบสามกลีบซ้อนกันเป็นชุด"),
        ("หมุด", "mut", "ใช้กลัดกลีบกับฐาน"),
        ("ธูป", "thup", "ธูป"),
        ("เทียน", "thian", "เทียน"),
        ("สะเดาะเคราะห์", "sado khro", "ปัดเคราะห์ร้าย"),
        ("พระแม่คงคา", "phra mae khongkha", "แม่แห่งน้ำ"),
        ("ยี่เป็ง", "yi peng", "วันเพ็ญเดือนยี่ของล้านนา"),
        ("ลอยโขมด", "loi khamot", "คำล้านนา ลอยไฟ"),
        ("สะเปา", "sapao", "คำล้านนา กระทงรูปเรือ ใส่ของทาน"),
        ("กระทงหน้อย", "krathong noi", "คำล้านนา กระทงเล็ก"),
        ("กระทงใหญ่", "krathong yai", "กระทงใหญ่ในขบวนแห่"),
        ("สะพานนวรัฐ", "saphan nawarat", "สะพานนวรัฐ"),
    ],
})

for lang in ("en", "th"):
    for st, ln in zip(UI[lang]["fold_steps"], LINES):
        st["line"] = ln
    for k in ("coin_g", "rho_default", "ping_src"):
        UI[lang].setdefault(k, UI["en"][k])
    UI[lang]["petals_per_leaf"] = 1
    UI[lang]["counts"] = COUNTS

_pp = os.path.join(os.path.dirname(os.path.abspath(__file__)), "photos.json")
PHOTOS = json.load(open(_pp)) if os.path.exists(_pp) else []
SOURCES = [
    ("กรมส่งเสริมวัฒนธรรม (Department of Cultural Promotion), ลอยกระทง, 2014", "https://image.mfa.go.th/mfa/0/pFxDf7ZYQ7/ไฟล์เอกสาร/ข้อมูลลอยกระทง_TH-EN.pdf"),
    ("Chiang Mai University, ลอยกระทง (Creative Knowledge), 4 Nov 2021", "https://accl.cmu.ac.th/Knowledge/details/2394"),
    ("Chiang Mai University Library, การเข้ามาของประเพณีลอยกระทง", "https://lannainfo.library.cmu.ac.th/lannatradition/yeepeng-comingkratong.php"),
    ("กรมศิลปากร, Chiang Mai National Museum, ประเพณียี่เป็ง, 2020", "https://www.finearts.go.th/chiangmaimuseum/view/21724"),
    ("Prince of Songkla University Library, วิธีการทำกระทง", "https://archive.clib.psu.ac.th/online-exhibition/loykratong/page8.html"),
    ("ThaiGoodView, การพับใบตองแบบต่าง ๆ, 29 Nov 2009", "https://www.thaigoodview.com/knowledge/4403/folding-banana-leaves"),
    ("TCDC Resource Center, ม้วน พับ จับจีบ เย็บกลีบใบตอง (2012), contents", "https://library.tcdc.or.th/record/view/b00032078"),
    ("Suan Dusit University, ศิลปะประดิษฐ์กับงานใบตองสด, 2023", "https://food.dusit.ac.th/main/wp-content/uploads/2023/03/ศิลปะงานใบตอง.pdf"),
    ("กรมประชาสัมพันธ์, ประเพณีลอยกระทง, 2026", "https://www.prd.go.th/th/content/category/detail/id/31/iid/510179"),
    ("Royal Irrigation Department, hydro-1, station P.1 Nawarat Bridge: monthly flow, rating curves, cross-sections", "https://www.hydro-1.net/main/4-RUNOFF.php"),
    ("University of Hamburg Botanical Garden, banana pseudostems, 15 Jan 2025", "https://www.botanischer-garten.uni-hamburg.de/01ueber-uns/aktuelle-meldungen/sfb-bananen-pseudostaemme.html"),
    ("PPTV, Loy Krathong 2026 date, 2 Oct 2026", "https://www.pptvhd36.com/news/ไลฟ์สไตล์/283924"),
    ("Chiangmai News, ประเพณีเดือนยี่เป็งเชียงใหม่ 2569, 23 Sep 2026", "https://www.chiangmainews.co.th/news/chiangmai/4138857/"),
    ("Thansettakij, Chiang Mai Yi Peng 2025 venues, 4 Nov 2025", "https://www.thansettakij.com/lifestyle/travel-shopping/643212"),
    ("Chiang Mai Public Relations Office, ยี่เป็งริมปิง, 5 Nov 2025", "https://chiangmai.prd.go.th/th/content/category/detail/id/9/iid/438616"),
    ("Thairath, rafts on the Ping for floating, 18 Nov 2021", "https://www.thairath.co.th/news/local/north/2245311"),
    ("Chiang Mai CityLife, the aftermath of Loy Krathong (Tha Wang Tan weir), 19 Nov 2013", "https://www.chiangmaicitylife.com/citynews/local/the-aftermath-of-loy-krathong/"),
    ("Thai PBS, Bangkok krathong count 2017, 4 Nov 2017", "https://www.thaipbs.or.th/news/content/267445"),
    ("Thai PBS, Bangkok krathong count 2018, 23 Nov 2018", "https://www.thaipbs.or.th/news/content/275875"),
    ("Thai PBS, Bangkok krathong count 2019, 12 Nov 2019", "https://www.thaipbs.or.th/news/content/285980"),
    ("Thai PBS, Bangkok krathong count 2020, 1 Nov 2020", "https://www.thaipbs.or.th/news/content/297939"),
    ("Sanook, Bangkok krathong count 2021, 20 Nov 2021", "https://www.sanook.com/news/8476438/"),
    ("InfoQuest, Bangkok krathong count 2022, 9 Nov 2022", "https://www.infoquest.co.th/?p=249125"),
    ("Thairath, Bangkok krathong counts 2023 and 2024, 16 Nov 2024", "https://www.thairath.co.th/news/local/bangkok/2825896"),
    ("PPTV, Bangkok krathong count 2025, 6 Nov 2025", "https://www.pptvhd36.com/news/สังคม/260859"),
    ("Khaosod English, Bangkok krathong count 2016, 15 Nov 2016", "https://www.khaosodenglish.com/news/bangkok/2016/11/15/bangkok-wakes-less-loy-krathong-mess-usual/"),
    ("Bangkok Post, Bangkok krathong count 2015", "https://www.bangkokpost.com/thailand/general/777357/"),
    ("Thai PBS, how long krathong materials take to break down, 8 Nov 2022", "https://www.thaipbs.or.th/news/content/321263"),
    ("US Naval Observatory, moon phases 2026", "https://aa.usno.navy.mil/api/moon/phases/year?year=2026"),
]
